### ISSUE TITLE
Баг в настройках игры

### ISSUE THREAD

**Issue by Earthman10** [SaPeUlDi/Grumpy-Three-Friends#17]
В настройках игры не работает полноэкранный режим.
Нажимаешь на на поле с галочкой. В любом состоянии ничего не происходит.
![image](https://user-images.githubusercontent.com/43227967/47666481-7606d680-dbc5-11e8-93a4-c21f66df458c.png)
![image](https://user-images.githubusercontent.com/43227967/47666491-7a32f400-dbc5-11e8-9827-0729a0d45e3f.png)

**Comment by Lofetty** [comment]
теперь работает
