### ISSUE TITLE
Баг с анимацией персонажа лягушка

### ISSUE THREAD

**Issue by Earthman10** [SaPeUlDi/Grumpy-Three-Friends#21]
Нет анимации движения персонажа.
При нажатии стрелок на клавиатуре (_кнопки управления движения_), **статичный спрайт** персонажа просто **скользит**.
При отпускании клавиши стрелки "вправо"/стрелки "влево" (кнопки движения "влево/вправо"), лягушка ещё какое-то время продолжает скользить.
https://i.gyazo.com/9ee87f8df772b1a275c0ca6fe79e6af0.mp4

**Comment by Lofetty** [comment]
анимаций и не было) и да, движение кривое и не полное) я не успел к Сб.. это ж не флеш тебе, чтоб я знал, как чего сделать))

**Comment by Lofetty** [comment]
качество перемещения исправлено. Анимация пока непрерывная, пока не пойму, как её остановить)
